### ISSUE TITLE
Tasks aren't remounted on workflow advance

### ISSUE THREAD

**Issue by blainelewis1** [hcikit/hcikit#1]
If a task relies on state the state won't be reset when the workflow advances. This can be problematic if the user isn't aware of the functionality. 

We do this on purpose because mounting components is expensive and it would be cheaper to reset your state when props change using an effect. However, it wouldn't be unreasonable to create a setting that allows a user to reset it. Implementing this wouldn't be too hard and addresses an already standing issue regarding the key prop. 

Example fix: https://stackoverflow.com/a/49374572/1036813

We could be smarter and make the key something like key={`${taskName}${index}${trialNumber}`} where trialNumber is optional. It also makes me wonder what happens if you try to mount the same task twice.

**Comment by blainelewis1** [comment]
Regardless of how this is implemented it's important we document this in the tasks section of the documentation.

**Comment by QuentinRoy** [comment]
I don't think mounting component is that expensive. Reconciliation is what takes time, but it often happens regardless (unless you are using memo, which is unneeded most of the time). Also, Thi sis not something that would happen much. At best, we are talking about one mount every few hundred ms, but many tasks would actually be much longer that this. Back to the point, I believe going out of your way just to make sure the Task instance is recycled looks like premature optimization to me.

In any case, I might be wrong but from what I have seen, it does not seem to happen. I.e. I do get a new instance of a Task every time. I think this is a reasonable behaviour (more on that later), but it must to be **consistent**. It would be problematic if some instances a recycled (which would preserve their state for example), and some instances are not.

IMHO, the decision point is what state/effect management you want to prioritize.
- I would argue trials need to be as independent as possible, and thus, any local state should be reset (i.e. you get a new instance).
- I also tend to assume, when using `useState(default)`, that the default will be taken on every different trials. It does look closer to my own mental model. And makes it easy to init a state from an init prop.
- I also tend to assume that a no dependency effect, e.g. `useEffect(() => { /* a get request or something */ }, [])`, would happen every time I am starting a new trial since it would be in the body of my trial component.
This is subjective, and maybe you would rather have a more "stateful" approach of trials. It is still possible to reset the state of a component manually by comparing old and new props (though it is kind of a pain, and particularly hard with hooks with which you would need to maintain a ref). It is also a kind of semi-controlled semi-uncontrolled form of component that I would dislike to write. My two cents. It is also possible to make sure an effect is run on every trial by adding the num of the trial as a dep (maybe this is the way you intended it to be used). Again, I am not a big fan, but if this is the model you have in mind, why not.

**Comment by blainelewis1** [comment]
This is especially evident in the last example task, where the state isn't reset as there's a bug in the task.
